[WIP] Fix/store lennard variant
elseu/sdu-oidc-jwt-client pull request #10
Opened 2020-11-18 14:58 UTC by LennardWesterveld

2020-11-19 13:50 UTC, daphnesmit commented on src/store.ts
> +      userInfo: userInfoPersistentValue ? JSON.parse(userInfoPersistentValue) : undefined,
maybe use safe json parse with fallbackvalue undefined (you never know)

2020-11-19 13:53 UTC, daphnesmit commented on src/store.ts
> +            .finally(() => {
finally is not supported in IE11.

If we use promises so we dont have to use async wait. then we should not do that. otherwise we might just uses async await after all..

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally

2020-11-19 13:54 UTC, daphnesmit commented on src/store.ts
> +              if (redirect) {
fail fast
if(!redirect) return

2020-11-19 13:55 UTC, daphnesmit requested changes
I like it a lot. just tiny thingie

2020-11-19 14:00 UTC, daphnesmit commented on src/store.ts
> +            .finally(() => {
Cant you just use then?

2020-11-19 14:18 UTC, LennardWesterveld commented on src/store.ts
> +              if (redirect) {
als geen redirect is moet hij als nog sessie controleren of userinfo update dus dat gaat niet op denk ik?

2020-11-23 20:21 UTC, sbesselsen requested changes

2020-11-23 20:21 UTC, sbesselsen commented on rollup.config.js
> +  external: ['events'],
Deze wordt toch überhaupt niet meer gebruikt in deze versie? Die gebruikte ik alleen voor EventEmitter op de client.

2020-11-23 20:21 UTC, sbesselsen commented on README.md
> +
Beetje onnodig ;)

2020-11-23 20:21 UTC, sbesselsen commented on src/stories/Login.stories.tsx
>          alert('No token!');
Ik snap waarom je wilt supporten dat je de API ook kunt testen zonder token; dat is best logisch. Maar waarom dan alsnog de alert erin laten?

2020-11-23 20:21 UTC, sbesselsen commented on src/OidcJwtProvider.tsx
> +  const context: OidcJwtContextData = useMemo(() => ({ useStore }), [useStore]);
Beetje onbenullig misschien, maar is het niet handiger om de context zelf in de ref te zetten waar je nu const useStoreRef = ... doet? Dan kun je doen const { useStore } = context en heb je deze hele useMemo hier ook niet meer nodig. Net even wat cleaner.

2020-11-23 20:21 UTC, sbesselsen commented on src/store.ts
> +interface AnyObject {
Waarom het hier AnyObject noemen en direct daaronder weer Params? Waarom niet gewoon Params? Dit type beschrijft toch niet "any object"? (wel als de values unknown type waren, maar string type is niet any object).

2020-11-24 09:30 UTC, LennardWesterveld commented on src/OidcJwtProvider.tsx
> +  const context: OidcJwtContextData = useMemo(() => ({ useStore }), [useStore]);
ik denk dat je het zo bedoeld 
`return <OidcJwtContext.Provider value={{ useStore }}>{children}</OidcJwtContext.Provider>;`

2020-11-24 09:31 UTC, LennardWesterveld commented on src/OidcJwtProvider.tsx
> +  const context: OidcJwtContextData = useMemo(() => ({ useStore }), [useStore]);
maar dan heb je telkens een nieuw object dat wil je ook niet hmmz

2020-11-24 09:52 UTC, daphnesmit approved these changes

2020-11-24 10:03 UTC, sbesselsen commented on src/OidcJwtProvider.tsx
> +  const context: OidcJwtContextData = useMemo(() => ({ useStore }), [useStore]);
Nee, dat bedoel ik niet. Ik zal een PR maken met wat ik bedoel :D

2020-11-24 10:14 UTC, merged