fix: allow for public site with no client
elseu/sdu-oidc-jwt-client pull request #51
Opened 2022-12-06 11:51 UTC by daphnesmit

2022-12-06 11:57 UTC, tpdewolf commented on src/OidcJwtProvider.tsx
> +  client?: OidcJwtClientOptions;
```suggestion
  client: OidcJwtClientOptions | false;
```

2022-12-06 11:59 UTC, tpdewolf requested changes
Dacht misschien mooier om client nog wel expliciet te moeten zetten van de types

2022-12-06 19:03 UTC, daphnesmit commented
> Dacht misschien mooier om client nog wel expliciet te moeten zetten van de types

heb het aangepast maar wel iets meer tenary in de store nu omdat je niet kan optional chainen

2022-12-06 19:06 UTC, tpdewolf approved these changes

2022-12-07 09:04 UTC, skarnl commented on src/store.ts
> +  options: OidcJwtClientOptions | false,
above this is called `client` - maybe we want to keep this variable-name consistent?

2022-12-07 13:00 UTC, merged